algoritmo "semnome"
var
p,s,m:real
inicio
ESCREVAL("-------------------------")
ESCREVAL ("ESCOLA JAVALI CANSADO")
ESCREVAL("-------------------------")
ESCREVAL("Primeira nota:")
leia(p)
escreval("segunda nota:")
leia(S)
escreval("-------------------------")
m<- (p+s)/2
escreval("MEDIA:" ,M)
se (m>=7)entao
escreval("ALUNO APROVADO")
senao
escreval("ALUNO REPROVADO")
fimse
ESCREVA("--------------------------")
fimalgoritmo